version: '3'

services:
  web:
    image: nginx:1-alpine
    ports:
     - "8001:80"
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - .:/usr/share/nginx/html
  php:
    image: php:7-fpm-alpine
    volumes:
     - .:/var/www/html
